### ISSUE TITLE
missing ios build

### ISSUE THREAD

**Issue by faiztechx01** [CCExtractor/Deluge-mobile-remote-client#19]
it is best mobile client ever that i had used. missing ios version.

streaming capability make this app good cause deluge it self donot have streaming ability.

hope u people will release ios version soon

**Comment by Erarshad** [comment]
> it is best mobile client ever that i had used. missing ios version.
> 
> streaming capability make this app good cause deluge it self donot have streaming ability.
> 
> hope u people will release ios version soon

ios version is under experiment it will release soon, thank you
