### ISSUE TITLE
App connect to the server but shows that deluge is unresponsive

### ISSUE THREAD

**Issue by N4v41** [CCExtractor/Deluge-mobile-remote-client#36]
Just trying the app but I can't see my torrents the app shows that deluge is unresponsive. How can I see advanced logs in the app to fix this?
![Screenshot_20211221-154258__01.jpg](https://user-images.githubusercontent.com/45365461/146982050-6b421001-2ff5-43b5-a872-0d78822f8504.jpg)

**Comment by Erarshad** [comment]
you can see the logs in deluge nginx logs

**Comment by geotibi** [comment]
Where do I see nginx logs? I got the same issue
