### ISSUE TITLE
Many unused imports

### ISSUE THREAD

**Issue by Pavel401** [CCExtractor/Deluge-mobile-remote-client#51]
**Describe the bug**
Unused imports
**To Reproduce**
The whole project consists of so many unused imports errors.

![unused import](https://user-images.githubusercontent.com/47685150/150637124-bcbe4cc4-2763-4960-992d-6f75d87c4d66.png)

**Environment**
- Device/emulator being used: <device version/Pixel 2 XL>
- OS ( Android); If Android then android version: <Android : 11>
- Flutter version: <2.8>

**Are you working on this issue? (Yes/No)**
Yes

**Comment by ItsAdityaKSingh** [comment]
This issue is already being taken care of in #50. Opening other issues with the same objective could be confusing.
